apiVersion: v1
kind: Service
metadata:
  name: cloud-native-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # TO DO: Migrate to modern AWS Load Balancer Controller, also Auto Mode cluster 
  
spec:
  selector:
    app: cloud-native-app # Ensure this matches the label in Deployment for pods

    type: LoadBalancer

    ports:
      - protocol: TCP
        port: 80
        targetPort: 5000