name: CI Pipeline

# Triggers
on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'

# Avoid race conditions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true   # save resources/money

# Jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: dev
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    # TODO: Migrate this step to GitHub Actions OIDC-based authentication for AWS instead of using long-lived secrets.
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    # replaced authorization token method that uses get-login-password command
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # setup-buildx-action enables multi-platform images building and export caching
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # build-push-action supports caching and multiple tags, much better than run:
    - name: Build, tag and push Docker image to Amazon ECR
      uses: docker/build-push-action@v6
      with:
        context: ./app
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
